### ISSUE TITLE
Installation of RabbitMQ plugins?

### ISSUE THREAD

**Issue by corstian** [dokku/dokku-rabbitmq#55]
Both the config dir and data dir do not contain any plugins possibly installed with RabbitMQ.

My brain tells me it should be quite straightforward to provide a RabbitMQ plugin through the data directory, install it within the container, and have it persist in the configuration.

Would this be possible? Or otherwise, how would it be possible to install RabbitMQ plugins without having them disappear after a container redeploy?

**Comment by sec0ndhand** [comment]
@josegonzalez I was hoping to use MQTT as a plugin on RabbitMQ, since I can't get it to work as an app using MQTT.  If I did some work on this, would this be a pull request you would accept? Maybe allowing for the plugins [shipped with RabbitMQ](https://www.rabbitmq.com/plugins.html#plugin-tiers) to be added? this may not help @corstian though, what do you think?

Also here is what I have tried as an app if maybe that is the easier fix:
```bash
dokku apps:create broker
docker pull cyrilix/rabbitmq-mqtt:latest
docker tag cyrilix/rabbitmq-mqtt:latest dokku/broker:v1
dokku config:set broker RABBITMQ_DEFAULT_USER=user RABBITMQ_DEFAULT_PASS=password
dokku tags:deploy broker v1
```

**Comment by josegonzalez** [comment]
Could you provide the plugins in a custom image for your rabbitmq service? So build a custom docker image and then when creating the service, specify that image for use.

**Comment by sec0ndhand** [comment]
Sorry for the long pause in between responses here.  I ended up using a custom image for MQTT  `cyrilix/rabbitmq-mqtt` and that allowed for MQTT to be running.  However, using the expose command `dokku rabbitmq:expose <app_name>` wouldn't work because the mqtt ports aren't exposed since they aren't included in the config of this plugin.  So I tracked down the command and pulled out the variables to expose just the MQTT portions of the app:

```bash
export RABBITMQ_IMAGE_VERSION=3.7
export RABBITMQ_IMAGE="cyrilix/rabbitmq-mqtt"
dokku rabbitmq:create mqtt
docker run -d --link "dokku.rabbitmq.mqtt:rabitmq" --name "dokku.rabbitmq.mqtt.ambassador" -p 1883:1883 -p 8883:8883 --restart always --label dokku=ambassador --label "dokku.ambassador=rabitmq" "dokku/ambassador:latest"
```
notice some of those commands are specific to the service name, so `"dokku.rabbitmq.mqtt:rabitmq"` is really `"dokku.rabbitmq.<SERVICE_NAME>:rabitmq"`

And if you want to remove it:
```bash
sudo docker rm --force dokku.rabbitmq.mqtt.ambassador
```

In order to login using the generated password and username, I had to add a vhost `/` using the web interface here:

`http://<host_name_or_IP>:15672/#/vhosts`

I don't know if there is a better way to expose custom ports on a plugin/service but this will at least get someone else up and going that wants to use the broker functionality.

**Comment by nileio** [comment]
@josegonzalez @sec0ndhand is there an update on this issue please?
could it be possible to expose any container port to the rabbitmq service? I am also facing similar issue where I need stomp plugin ports exposed. Though I followed @josegonzalez suggestion to create a customer dockerimage and use that, the plugin ports cant be exposed.

**Comment by nileio** [comment]
it ended up to be a small change actually. I modified `config` and added ports to `PLUGIN_DATASTORE_PORTS` then I used my modified `Dockerfile` which includes the enabled plugins. Alternatively you can also modify `Dockerfile` of the plugin too and use your own fork url to install the plugin. everything seem to be working as expected and still get the awesomeness of dokku.
modified config and Dockerfile at
https://github.com/mavenea/dokku-rabbitmq

**Comment by josegonzalez** [comment]
The correct way to implement this is to use a custom Dockerfile based on the upstream image, and install the plugins in there. 

It might be nice to add custom ports to the list of exposed ports, especially for custom images. If someone would like to file an issue for this in the dokku-redis repository (where I track all cross-service enhancements), that would be awesome.
